# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhotosTimeStamper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhotosTimeStamper

  target 'PhotosTimeStamperTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PhotosTimeStamperUITests' do
    # Pods for testing
  end

end
